"""Seed data for milestones plugin — categories, templates, leaps."""

import json

SYSTEM_CATEGORIES = [
    {"name": "Grobmotorik", "color": "#209fb5", "icon": "move"},
    {"name": "Feinmotorik", "color": "#1e66f5", "icon": "hand"},
    {"name": "Sprache", "color": "#7287fd", "icon": "message-circle"},
    {"name": "Kognition", "color": "#8839ef", "icon": "brain"},
    {"name": "Soziales", "color": "#ea76cb", "icon": "heart"},
    {"name": "Gesundheit", "color": "#40a02b", "icon": "shield"},
    {"name": "Familienerinnerungen", "color": "#fe640b", "icon": "camera"},
    {"name": "Spruenge", "color": "#df8e1d", "icon": "zap"},
]

MILESTONE_TEMPLATES = [
    # === Grobmotorik (medical) === sort_order 1-9
    {"title": "Kopf halten", "description": "Stabiles Halten des Kopfes in aufrechter Position", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 8, "suggested_age_weeks_max": 16, "sort_order": 1},
    {"title": "Drehen Bauch/Ruecken", "description": "Selbststaendiges Drehen vom Bauch auf den Ruecken und umgekehrt", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 16, "suggested_age_weeks_max": 26, "sort_order": 2},
    {"title": "Freies Sitzen", "description": "Sitzen ohne Unterstuetzung", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 26, "suggested_age_weeks_max": 35, "sort_order": 3},
    {"title": "Krabbeln/Robben", "description": "Fortbewegung durch Krabbeln oder Robben", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 30, "suggested_age_weeks_max": 43, "sort_order": 4},
    {"title": "An Moebeln hochziehen", "description": "Selbststaendiges Hochziehen zum Stand an Moebeln", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 35, "suggested_age_weeks_max": 43, "sort_order": 5},
    {"title": "Erste freie Schritte", "description": "Erste Schritte ohne Festhalten", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 43, "suggested_age_weeks_max": 65, "sort_order": 6},
    {"title": "Sicheres Laufen", "description": "Stabiles, sicheres Laufen ohne Hilfe", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 56, "suggested_age_weeks_max": 78, "sort_order": 7},
    {"title": "Treppensteigen mit Festhalten", "description": "Treppensteigen mit Festhalten am Gelaender oder an der Hand", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 8},
    {"title": "Rennen, Huepfen mit beiden Beinen", "description": "Rennen und beidbeinigens Huepfen", "category": "Grobmotorik", "source_type": "medical", "suggested_age_weeks_min": 104, "suggested_age_weeks_max": 104, "sort_order": 9},

    # === Feinmotorik (medical) === sort_order 10-17
    {"title": "Hand oeffnen, Greifreflex verliert sich", "description": "Haende oeffnen sich zunehmend, der Greifreflex laesst nach", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 12, "suggested_age_weeks_max": 12, "sort_order": 10},
    {"title": "Gezieltes Greifen", "description": "Bewusstes, gezieltes Greifen nach Gegenstaenden", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 16, "suggested_age_weeks_max": 26, "sort_order": 11},
    {"title": "Gegenstand von Hand zu Hand", "description": "Uebergabe eines Gegenstands von einer Hand in die andere", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 26, "suggested_age_weeks_max": 30, "sort_order": 12},
    {"title": "Pinzettengriff", "description": "Greifen kleiner Gegenstaende mit Daumen und Zeigefinger", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 39, "suggested_age_weeks_max": 52, "sort_order": 13},
    {"title": "Loeffel halten", "description": "Selbststaendiges Halten eines Loeffels", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 52, "suggested_age_weeks_max": 65, "sort_order": 14},
    {"title": "Turm aus 2-3 Kloetzen", "description": "Stapeln von 2-3 Kloetzen zu einem Turm", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 65, "suggested_age_weeks_max": 78, "sort_order": 15},
    {"title": "Kritzeln", "description": "Erste Kritzelversuche mit Stift auf Papier", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 16},
    {"title": "Turm aus 6 Kloetzen", "description": "Stapeln von 6 Kloetzen zu einem Turm", "category": "Feinmotorik", "source_type": "medical", "suggested_age_weeks_min": 104, "suggested_age_weeks_max": 104, "sort_order": 17},

    # === Sprache (medical) === sort_order 18-26
    {"title": "Erstes Soziallaecheln", "description": "Erstes bewusstes Laecheln als Reaktion auf Gesichter", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 6, "suggested_age_weeks_max": 8, "sort_order": 18},
    {"title": "Lallen, Silbenketten", "description": "Aneinanderreihung von Silben wie bababa, dadada", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 26, "suggested_age_weeks_max": 39, "sort_order": 19},
    {"title": "Reagiert auf eigenen Namen", "description": "Dreht sich um oder reagiert auf den eigenen Namen", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 30, "suggested_age_weeks_max": 39, "sort_order": 20},
    {"title": "Erstes Wort mit Bedeutung", "description": "Erstes gezielt eingesetztes Wort", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 43, "suggested_age_weeks_max": 61, "sort_order": 21},
    {"title": "Zeigegeste", "description": "Zeigen mit dem Finger auf interessante Dinge", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 39, "suggested_age_weeks_max": 52, "sort_order": 22},
    {"title": "5-10 Woerter aktiv", "description": "Aktiver Wortschatz von 5-10 Woertern", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 65, "suggested_age_weeks_max": 65, "sort_order": 23},
    {"title": "Zwei-Wort-Saetze", "description": "Kombination von zwei Woertern zu einfachen Saetzen", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 24},
    {"title": "Ca. 50 Woerter aktiv", "description": "Aktiver Wortschatz von circa 50 Woertern", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 104, "suggested_age_weeks_max": 104, "sort_order": 25},
    {"title": "Versteht einfache Aufforderungen", "description": "Versteht und befolgt einfache sprachliche Anweisungen", "category": "Sprache", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 26},

    # === Kognition (medical) === sort_order 27-30
    {"title": "Blickkontakt halten", "description": "Bewusstes und anhaltendes Halten von Blickkontakt", "category": "Kognition", "source_type": "medical", "suggested_age_weeks_min": 8, "suggested_age_weeks_max": 12, "sort_order": 27},
    {"title": "Objektpermanenz", "description": "Verstaendnis, dass Objekte weiter existieren, auch wenn sie nicht sichtbar sind", "category": "Kognition", "source_type": "medical", "suggested_age_weeks_min": 35, "suggested_age_weeks_max": 52, "sort_order": 28},
    {"title": "Symbolspiel/So-tun-als-ob", "description": "Beginnendes symbolisches Spiel und Rollenspiel", "category": "Kognition", "source_type": "medical", "suggested_age_weeks_min": 65, "suggested_age_weeks_max": 78, "sort_order": 29},
    {"title": "Erkennt sich im Spiegel", "description": "Erkennt das eigene Spiegelbild als sich selbst", "category": "Kognition", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 30},

    # === Soziales (medical) === sort_order 31-34
    {"title": "Fremdeln", "description": "Angst oder Unbehagen gegenueber fremden Personen", "category": "Soziales", "source_type": "medical", "suggested_age_weeks_min": 26, "suggested_age_weeks_max": 39, "sort_order": 31},
    {"title": "Winken, Bye-Bye", "description": "Winken als Abschiedsgeste", "category": "Soziales", "source_type": "medical", "suggested_age_weeks_min": 39, "suggested_age_weeks_max": 52, "sort_order": 32},
    {"title": "Parallelspiel mit anderen Kindern", "description": "Spielt neben anderen Kindern, noch nicht miteinander", "category": "Soziales", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 104, "sort_order": 33},
    {"title": "Trotzphase beginnt", "description": "Beginn der Autonomiephase mit Widerstand und Trotzreaktionen", "category": "Soziales", "source_type": "medical", "suggested_age_weeks_min": 78, "suggested_age_weeks_max": 78, "sort_order": 34},

    # === Familienerinnerungen (emotional) — Erste Wochen === sort_order 100-111
    {"title": "Erste Nacht zu Hause", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 100},
    {"title": "Erste Autofahrt", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 101},
    {"title": "Erster Spaziergang", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 102},
    {"title": "Erster Besuch (Grosseltern, Freunde)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 103},
    {"title": "Erstes Bad zu Hause", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 104},
    {"title": "Erster Besuch bei den Grosseltern", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 105},
    {"title": "Erstes bewusstes Augenkontaktspiel", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 106},
    {"title": "Erstes Lachen/Glucksen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 107},
    {"title": "Erste Unterhaltung durch Laute", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 108},
    {"title": "Erstes gemeinsames Buch/Vorlesen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 109},
    {"title": "Erstes Kuscheltier, das bleibt", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 110},
    {"title": "Erstes Lieblingslied beim Einschlafen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 111},

    # === Familienerinnerungen (emotional) — Halbjahres-Phase === sort_order 112-124
    {"title": "Erstes festes Essen (Beikoststart)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 112},
    {"title": "Erstes Mal selbst etwas greifen und essen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 113},
    {"title": "Erster Zahn", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 114},
    {"title": "Erste durchgeschlafene Nacht", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 115},
    {"title": "Erste klare Vorliebe (Essen, Spielzeug, Person)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 116},
    {"title": "Erster Lieblings-Song zum Tanzen/Wippen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 117},
    {"title": "Erstes bewusstes Nein (nonverbal)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 118},
    {"title": "Erste Trotzreaktion", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 119},
    {"title": "Erster Ausflug in die Natur (Wald, See)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 120},
    {"title": "Erstes Mal barfuss im Gras", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 121},
    {"title": "Erstes Planschen (Badesee, Pool, Meer)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 122},
    {"title": "Erster Zoo-/Tierpark-Besuch", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 123},
    {"title": "Erstes Mal auf einem Spielplatz", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 124},

    # === Familienerinnerungen (emotional) — Um den 1. Geburtstag === sort_order 125-134
    {"title": "Erster Geburtstag", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 125},
    {"title": "Erstes frei gesprochenes Wort mit Bedeutung", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 126},
    {"title": "Erste Schritte", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 127},
    {"title": "Erstes eigenstaendiges Laufen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 128},
    {"title": "Erste Weihnachten (bewusst)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 129},
    {"title": "Erstes Silvester", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 130},
    {"title": "Erstes Ostern", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 131},
    {"title": "Erster Sommerurlaub", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 132},
    {"title": "Erster Schnee", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 133},
    {"title": "Erster Herbst mit Laubspielen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 134},

    # === Familienerinnerungen (emotional) — Zweites Lebensjahr === sort_order 135-164
    {"title": "Erstes bewusstes Mama / Papa", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 135},
    {"title": "Erstes Winken zum Abschied", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 136},
    {"title": "Erster Kuss", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 137},
    {"title": "Erste Umarmung (Kind initiiert)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 138},
    {"title": "Erstes Teilen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 139},
    {"title": "Erstes gemeinsames Spielen mit anderem Kind", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 140},
    {"title": "Erste beste Freundin/erster Freund", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 141},
    {"title": "Erster Zwei-Wort-Satz", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 142},
    {"title": "Erstes Ich / eigenen Namen benutzen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 143},
    {"title": "Erstes Lied mitsingen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 144},
    {"title": "Erste eigene Geschichte erzaehlen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 145},
    {"title": "Erster Witz", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 146},
    {"title": "Erstes Mal selbst aus dem Becher trinken", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 147},
    {"title": "Erstes Mal mit Loeffel/Gabel essen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 148},
    {"title": "Erstes Mal Zaehne putzen (selbst versuchen)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 149},
    {"title": "Erstes Mal Schuhe/Jacke anziehen versuchen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 150},
    {"title": "Erstes Mal Topf benutzen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 151},
    {"title": "Abstillen / letzte Flasche", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 152},
    {"title": "Umzug ins eigene Bett/Zimmer", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 153},
    {"title": "KiTa-Eingewoehnung: erster Tag", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 154},
    {"title": "KiTa: erster Tag ohne Traenen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 155},
    {"title": "KiTa: erste Freundschaft", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 156},
    {"title": "Erste Zugfahrt", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 157},
    {"title": "Erster Flug", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 158},
    {"title": "Erstes Konzert/Kinder-Event", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 159},
    {"title": "Erste Fahrradtour (Kindersitz/Anhaenger)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 160},
    {"title": "Erster Besuch im Museum", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 161},
    {"title": "Erstes Theaterstueck/Puppenspiel", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 162},

    # === Familienerinnerungen (emotional) — Besondere Momente === sort_order 163-172
    {"title": "Erstes Mal Ich hab dich lieb", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 163},
    {"title": "Erstes Mal troesten (jemand anderen)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 164},
    {"title": "Erstes Mal wirklich wuetend werden", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 165},
    {"title": "Erstes Mal aus eigenem Antrieb helfen", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 166},
    {"title": "Erstes gemaltes Bild", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 167},
    {"title": "Erstes Foto, das das Kind selbst macht", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 168},
    {"title": "Erste Obsession (Dinosaurier, Bagger, Tiere)", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 169},
    {"title": "Erstes Lieblingsbuch", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 170},
    {"title": "Erstes Lieblingskeidungsstueck", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 171},
    {"title": "Erstes Rollenspiel", "description": None, "category": "Familienerinnerungen", "source_type": "emotional", "suggested_age_weeks_min": None, "suggested_age_weeks_max": None, "sort_order": 172},
]

LEAP_DEFINITIONS = [
    {
        "leap_number": 1,
        "title": "Veraenderung der Sinneseinduecke",
        "description": "Das Baby nimmt seine Umwelt ploetzlich intensiver und differenzierter wahr. Sinneseinduecke werden bewusster verarbeitet.",
        "storm_start_weeks": 4.0,
        "storm_end_weeks": 6.0,
        "sun_start_weeks": 6.0,
        "new_skills": json.dumps([
            "Laengeres, aufmerksameres Wachsein",
            "Erstes echtes Laecheln als Reaktion",
            "Fixieren von Gesichtern und Objekten",
            "Traenen beim Weinen",
        ]),
        "storm_signs": json.dumps([
            "Vermehrtes Weinen, Unruhe",
            "Unregelmaessiger Schlaf",
            "Veraenderte Atmung, schnelleres Schrecken",
            "Starker Wunsch nach Koerperkontakt",
        ]),
        "sort_order": 1,
    },
    {
        "leap_number": 2,
        "title": "Welt der Muster",
        "description": "Das Baby erkennt einfache Muster in Sinneseinduecken, im eigenen Koerper und in der Umwelt.",
        "storm_start_weeks": 7.0,
        "storm_end_weeks": 10.0,
        "sun_start_weeks": 10.0,
        "new_skills": json.dumps([
            "Kontrolle ueber Kopfhaltung beginnt",
            "Gezielteres Greifen und Tasten nach Objekten",
            "Erkennen eigener Haende und Fuesse",
            "Erste Aah- und Uuh-Laute (Gurren)",
            "Reaktion auf Spiegelbilder",
        ]),
        "storm_signs": json.dumps([
            "Klammerverhalten, Weinen bei Ablegen",
            "Appetitprobleme, Trinkunlust",
            "Schlafprobleme",
            "Wirkt abwesend oder starrt laenger",
        ]),
        "sort_order": 2,
    },
    {
        "leap_number": 3,
        "title": "Welt der fliessenden Uebergaenge",
        "description": "Das Baby erkennt fliessende, kontinuierliche Veraenderungen - Stimmmodulation, Bewegungsablaeufe, Lichtwechsel.",
        "storm_start_weeks": 11.0,
        "storm_end_weeks": 11.5,
        "sun_start_weeks": 12.0,
        "new_skills": json.dumps([
            "Drehen vom Ruecken auf die Seite",
            "Weichere, kontrolliertere Bewegungen",
            "Mit Stimme spielen (Lautstaerke, Tonhoehe variieren)",
            "Dem Geschehen mit Augen folgen",
            "Erstes Lachen",
        ]),
        "storm_signs": json.dumps([
            "Schreckhaftigkeit",
            "Klammern, Stimmungsschwankungen",
            "Schlaeft schlechter ein",
            "Moechte mehr Aufmerksamkeit",
        ]),
        "sort_order": 3,
    },
    {
        "leap_number": 4,
        "title": "Welt der Ereignisse",
        "description": "Das Baby begreift, dass Ereignisse aus aufeinanderfolgenden Schritten bestehen. Ursache-Wirkung wird erahnt.",
        "storm_start_weeks": 14.0,
        "storm_end_weeks": 20.0,
        "sun_start_weeks": 20.0,
        "new_skills": json.dumps([
            "Gezieltes Greifen, Festhalten, Loslassen",
            "Objekte in den Mund nehmen, erkunden",
            "Drehen vom Ruecken auf den Bauch",
            "Silbenketten (bababa, dadada)",
            "Interesse an Nahrung der Erwachsenen",
        ]),
        "storm_signs": json.dumps([
            "Lange, intensive Phase mit viel Weinen",
            "Deutliche Schlafregression",
            "Appetitverlust oder Trinkstreiks",
            "Fremdeln kuendigt sich an",
            "Moechte permanent bei Bezugsperson sein",
        ]),
        "sort_order": 4,
    },
    {
        "leap_number": 5,
        "title": "Welt der Beziehungen",
        "description": "Das Baby begreift raeumliche und funktionale Beziehungen zwischen Dingen: drin/draussen, oben/unten, nah/fern.",
        "storm_start_weeks": 22.0,
        "storm_end_weeks": 26.0,
        "sun_start_weeks": 26.0,
        "new_skills": json.dumps([
            "Sitzen (anfangs mit Unterstuetzung)",
            "Krabbelvorbereitung, robben",
            "Objekte ineinander stecken, aufeinander stapeln",
            "Verstehen einfacher Woerter (Mama, nein)",
            "Beginn des Fremdelns",
        ]),
        "storm_signs": json.dumps([
            "Starkes Fremdeln, Trennungsangst",
            "Klammerverhalten verstaerkt",
            "Schlafregression",
            "Stimmungsschwankungen, Frustration",
        ]),
        "sort_order": 5,
    },
    {
        "leap_number": 6,
        "title": "Welt der Kategorien",
        "description": "Das Baby beginnt, Dinge zu kategorisieren: Hunde sind Hunde, Essen ist Essen, Baelle rollen. Abstraktion beginnt.",
        "storm_start_weeks": 33.0,
        "storm_end_weeks": 38.0,
        "sun_start_weeks": 37.0,
        "new_skills": json.dumps([
            "Sicheres Krabbeln",
            "Hochziehen zum Stand",
            "Pinzettengriff (Daumen-Zeigefinger)",
            "Sortiert Dinge spielerisch",
            "Imitiert Gesten (winken, klatschen)",
            "Erste bedeutungstragende Woerter",
        ]),
        "storm_signs": json.dumps([
            "Launenhaftigkeit, schnelle Stimmungswechsel",
            "Eifersucht, Anhaenglichkeit",
            "Neue Aengste (Staubsauger, fremde Raeume)",
            "Waehlerisch beim Essen",
            "Schlafprobleme",
        ]),
        "sort_order": 6,
    },
    {
        "leap_number": 7,
        "title": "Welt der Abfolgen",
        "description": "Das Kind versteht, dass Handlungen in bestimmter Reihenfolge ablaufen muessen, um ein Ziel zu erreichen.",
        "storm_start_weeks": 41.0,
        "storm_end_weeks": 47.0,
        "sun_start_weeks": 46.0,
        "new_skills": json.dumps([
            "Gezielte Handlungsketten (Puzzleteil nehmen, einsetzen)",
            "Erste Schritte an Moebeln entlang",
            "Geben und Nehmen-Spiele",
            "Wortschatz waechst (meist passiv)",
            "Versteht einfache Aufforderungen",
        ]),
        "storm_signs": json.dumps([
            "Trotzanfaelle in Vorform",
            "Sehr anhaenglich",
            "Unruhe, Frustration bei Misserfolg",
            "Appetit- und Schlafveraenderungen",
        ]),
        "sort_order": 7,
    },
    {
        "leap_number": 8,
        "title": "Welt der Programme",
        "description": "Das Kind versteht, dass Programme flexibel sind - dasselbe Ziel laesst sich auf verschiedenen Wegen erreichen.",
        "storm_start_weeks": 51.0,
        "storm_end_weeks": 55.0,
        "sun_start_weeks": 54.0,
        "new_skills": json.dumps([
            "Freies Stehen, erste freie Schritte",
            "Rollenspiel-Ansaetze (Puppe fuettern, telefonieren)",
            "Hilft beim Anziehen mit",
            "Wortkombinationen beginnen",
            "Zeigt auf Gewuenschtes, fuehrt Erwachsene",
        ]),
        "storm_signs": json.dumps([
            "Starkes Klammern, Trennungs-Drama",
            "Frustration und Wutausbrueche",
            "Widerstand bei Routinen",
            "Regression bei bereits Gekonntem",
            "Schlafprobleme",
        ]),
        "sort_order": 8,
    },
    {
        "leap_number": 9,
        "title": "Welt der Prinzipien",
        "description": "Das Kind erkennt Prinzipien hinter Programmen - Regeln, soziale Strategien, eigener Wille. Beginnende Autonomie.",
        "storm_start_weeks": 59.0,
        "storm_end_weeks": 65.0,
        "sun_start_weeks": 64.0,
        "new_skills": json.dumps([
            "Sicheres Laufen",
            "Testen von Grenzen, Nein als Konzept",
            "Erste Verhandlungen",
            "Empathie-Anzeichen (Troesten)",
            "Symbolisches Spiel nimmt zu",
        ]),
        "storm_signs": json.dumps([
            "Ausgeprägte Trotzphasen beginnen",
            "Stimmungsschwankungen extrem",
            "Eifersucht, Besitzanspruch",
            "Neue Aengste",
            "Schlaf- und Essprobleme",
        ]),
        "sort_order": 9,
    },
    {
        "leap_number": 10,
        "title": "Welt der Systeme",
        "description": "Das Kind begreift, dass Prinzipien zu Systemen zusammenwirken: Familie, Kita-Gruppe, Ich als Person.",
        "storm_start_weeks": 70.0,
        "storm_end_weeks": 76.0,
        "sun_start_weeks": 75.0,
        "new_skills": json.dumps([
            "Ich-Bewusstsein (Ich, Name verwenden)",
            "Spiegelerkennung sicher",
            "Laengere Saetze, Wortexplosion",
            "Komplexeres Rollenspiel",
            "Regelverstaendnis",
            "Erste Zeichen von Sauberkeit-Interesse",
        ]),
        "storm_signs": json.dumps([
            "Die klassische Autonomiephase startet voll",
            "Heftige Wutausbrueche",
            "Will alles selbst machen",
            "Regression bei Schlaf, Essen, manchmal Sprache",
            "Starke Anhaenglichkeit wechselt mit Abgrenzung",
        ]),
        "sort_order": 10,
    },
]
