"""add_sleep_plugin

Revision ID: 3d187e6274bb
Revises: 12657ff9f239
Create Date: 2026-04-19 16:34:57.341742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d187e6274bb'
down_revision: Union[str, None] = '12657ff9f239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaper_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diaper_type', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('consistency', sa.String(length=30), nullable=True),
    sa.Column('has_rash', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaper_entries', schema=None) as batch_op:
        batch_op.create_index('ix_diaper_entries_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_diaper_entries_child_time', ['child_id', 'time'], unique=False)
        batch_op.create_index('ix_diaper_entries_time', ['time'], unique=False)

    op.create_table('feeding_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feeding_type', sa.String(length=20), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=True),
    sa.Column('food_type', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_entries', schema=None) as batch_op:
        batch_op.create_index('ix_sleep_entries_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_sleep_entries_child_start', ['child_id', 'start_time'], unique=False)
        batch_op.create_index('ix_sleep_entries_start_time', ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_sleep_entries_start_time')
        batch_op.drop_index('ix_sleep_entries_child_start')
        batch_op.drop_index('ix_sleep_entries_child_id')

    op.drop_table('sleep_entries')
    op.drop_table('feeding_entries')
    with op.batch_alter_table('diaper_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_diaper_entries_time')
        batch_op.drop_index('ix_diaper_entries_child_time')
        batch_op.drop_index('ix_diaper_entries_child_id')

    op.drop_table('diaper_entries')
    # ### end Alembic commands ###
