"""add_tummy_time_entries_table

Revision ID: 918c43c44db8
Revises: 9d613e342b6f
Create Date: 2026-04-21 08:16:18.431429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918c43c44db8'
down_revision: Union[str, None] = '9d613e342b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tummy_time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tummy_time_entries', schema=None) as batch_op:
        batch_op.create_index('ix_tummy_time_entries_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_tummy_time_entries_child_start', ['child_id', 'start_time'], unique=False)
        batch_op.create_index('ix_tummy_time_entries_start_time', ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tummy_time_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_tummy_time_entries_start_time')
        batch_op.drop_index('ix_tummy_time_entries_child_start')
        batch_op.drop_index('ix_tummy_time_entries_child_id')

    op.drop_table('tummy_time_entries')
    # ### end Alembic commands ###
