"""add_health_entries_table

Revision ID: 9d613e342b6f
Revises: 306ee614935b
Create Date: 2026-04-21 08:07:43.841868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d613e342b6f'
down_revision: Union[str, None] = '306ee614935b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_entries', schema=None) as batch_op:
        batch_op.create_index('ix_health_entries_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_health_entries_child_time', ['child_id', 'time'], unique=False)
        batch_op.create_index('ix_health_entries_time', ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_health_entries_time')
        batch_op.drop_index('ix_health_entries_child_time')
        batch_op.drop_index('ix_health_entries_child_id')

    op.drop_table('health_entries')
    # ### end Alembic commands ###
