"""add vitamind3 plugin table

Revision ID: bee6c210fce0
Revises: e94350312347
Create Date: 2026-04-19 21:50:52.197738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee6c210fce0'
down_revision: Union[str, None] = 'e94350312347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vitamind3_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'date', name='uq_vitamind3_child_date')
    )
    with op.batch_alter_table('vitamind3_entries', schema=None) as batch_op:
        batch_op.create_index('ix_vitamind3_entries_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_vitamind3_entries_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitamind3_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_vitamind3_entries_date')
        batch_op.drop_index('ix_vitamind3_entries_child_id')

    op.drop_table('vitamind3_entries')
    # ### end Alembic commands ###
