"""Plugin package — auto-discovery via filesystem scan (ADR-1).

Public API:
    - PluginBase: Abstract base class for all plugins.
    - WidgetDef: Dashboard widget definition dataclass.
    - plugin_registry: Module-level PluginRegistry singleton.
    - discover_plugins(): Convenience function for plugin discovery.
    - discover_models(): Import all plugin modules for Alembic model discovery.
"""

from app.plugins._base import PluginBase, WidgetDef  # noqa: F401
from app.plugins.registry import plugin_registry  # noqa: F401


def discover_plugins() -> list[PluginBase]:
    """Discover all plugins and return them as a list.

    Convenience wrapper around ``plugin_registry.discover()``.
    Idempotent — already-registered plugins are not duplicated.
    """
    plugin_registry.discover()
    return plugin_registry.get_all()


def discover_models() -> None:
    """Import all plugin modules so Alembic discovers their SQLAlchemy models.

    Called from ``alembic/env.py`` to ensure all plugin tables
    are included in autogenerated migrations.
    """
    from pathlib import Path

    from app.plugins.registry import _import_plugin_modules

    _import_plugin_modules(Path(__file__).parent)
